sudo: required
services:
  - docker

before_install:
  - docker build -t robmacg92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true robmacg92/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-app"
  env: "Docker-app-env"
  bucket_name: "elasticbeanstalk-eu-west-2-041021990321"
  bucket_path: "docker-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"